In [2]:
import numpy as np
arr=np.array([1,2,3])
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr_2d)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [22]:
print(np.zeros((3,3)))
print()
print(np.ones((2,4)))
print()
print(np.eye(3))
print()
print(np.arange(0,10,2))
print()
print(np.linspace(0,1,5))
print()
print(np.random.rand(3,2))
print()
print(np.random.randn(3,2))



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[0 2 4 6 8]

[0.   0.25 0.5  0.75 1.  ]

[[0.9275931  0.27255162]
 [0.47234368 0.44924182]
 [0.61699104 0.41140854]]

[[-0.56970228 -0.44282879]
 [ 0.9511245   0.10942161]
 [ 0.51391263  0.41881049]]


In [23]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


In [25]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a*b)
print(np.sin(a))

[5 7 9]
[ 4 10 18]
[0.84147098 0.90929743 0.14112001]


In [27]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.dot(a,b))
print(a@b)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [29]:
arr=np.array([[1,2,3,4],[3,4,5,6]])
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.std())

28
3.5
6
1
1.5


In [30]:
arr=np.array([1,2,3,4,5])
print(arr[0])
print(arr[1:4])
print(arr[::2])

1
[2 3 4]
[1 3 5]


In [31]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr[0,1])
print(arr[:,1])
print(arr[1,:2])

2
[2 5]
[4 5]


In [32]:
arr=np.array([1,2,3,4,5])
mask=arr>3
print(arr[mask])

[4 5]
